<?php

class m141224_021845_create_authenticated_user_permissions_and_assign_it_to_saad extends CDbMigration {
	public function up() {
		$this->execute("
SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
SET time_zone = '+00:00';

--
-- Database: `sadaqat_online`
--

-- --------------------------------------------------------

--
-- Table structure for table `auth_assignment`
--

DROP TABLE IF EXISTS `auth_assignment`;
CREATE TABLE IF NOT EXISTS `auth_assignment` (
  `itemname` varchar(64) NOT NULL,
  `userid` varchar(64) NOT NULL,
  `bizrule` text,
  `data` text,
  PRIMARY KEY (`itemname`,`userid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `auth_assignment`
--

INSERT INTO `auth_assignment` (`itemname`, `userid`, `bizrule`, `data`) VALUES
('Admin', '1', NULL, 'N;'),
('Authenticated', '2', NULL, 'N;');

-- --------------------------------------------------------

--
-- Table structure for table `auth_item`
--

DROP TABLE IF EXISTS `auth_item`;
CREATE TABLE IF NOT EXISTS `auth_item` (
  `name` varchar(64) NOT NULL,
  `type` int(11) NOT NULL,
  `description` text,
  `bizrule` text,
  `data` text,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `auth_item`
--

INSERT INTO `auth_item` (`name`, `type`, `description`, `bizrule`, `data`) VALUES
('Admin', 2, NULL, NULL, 'N;'),
('Admin.Beneficiary.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiary.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiary.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiary.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiary.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiary.View', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarydisabled.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiarydisabled.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarydisabled.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarydisabled.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarydisabled.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarydisabled.View', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryfamilymembers.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiaryfamilymembers.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryfamilymembers.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryfamilymembers.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryfamilymembers.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryfamilymembers.View', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryfinance.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiaryfinance.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryfinance.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryfinance.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryfinance.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryfinance.View', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryhome.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiaryhome.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryhome.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryhome.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryhome.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryhome.View', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryorphan.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiaryorphan.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryorphan.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryorphan.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryorphan.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryorphan.View', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarypaterfamilias.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiarypaterfamilias.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarypaterfamilias.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarypaterfamilias.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarypaterfamilias.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarypaterfamilias.View', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarypoor.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiarypoor.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarypoor.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarypoor.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarypoor.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarypoor.View', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryrelation.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiaryrelation.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryrelation.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryrelation.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryrelation.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryrelation.View', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryresearchnotes.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiaryresearchnotes.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryresearchnotes.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryresearchnotes.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryresearchnotes.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryresearchnotes.View', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarystudent.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiarystudent.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarystudent.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarystudent.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarystudent.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarystudent.View', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarystudentclass.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiarystudentclass.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarystudentclass.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarystudentclass.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarystudentclass.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarystudentclass.View', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryteacher.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiaryteacher.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryteacher.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryteacher.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryteacher.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiaryteacher.View', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarywidow.*', 1, NULL, NULL, 'N;'),
('Admin.Beneficiarywidow.Admin', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarywidow.Create', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarywidow.Index', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarywidow.Update', 0, NULL, NULL, 'N;'),
('Admin.Beneficiarywidow.View', 0, NULL, NULL, 'N;'),
('Admin.City.*', 1, NULL, NULL, 'N;'),
('Admin.City.Admin', 0, NULL, NULL, 'N;'),
('Admin.City.Create', 0, NULL, NULL, 'N;'),
('Admin.City.GetCities', 0, NULL, NULL, 'N;'),
('Admin.City.Index', 0, NULL, NULL, 'N;'),
('Admin.City.Update', 0, NULL, NULL, 'N;'),
('Admin.City.View', 0, NULL, NULL, 'N;'),
('Admin.Country.*', 1, NULL, NULL, 'N;'),
('Admin.Country.Admin', 0, NULL, NULL, 'N;'),
('Admin.Country.Create', 0, NULL, NULL, 'N;'),
('Admin.Country.Index', 0, NULL, NULL, 'N;'),
('Admin.Country.Update', 0, NULL, NULL, 'N;'),
('Admin.Country.View', 0, NULL, NULL, 'N;'),
('Admin.Default.*', 1, NULL, NULL, 'N;'),
('Admin.Default.Error', 0, NULL, NULL, 'N;'),
('Admin.Default.Index', 0, NULL, NULL, 'N;'),
('Admin.Default.Login', 0, NULL, NULL, 'N;'),
('Admin.Default.Logout', 0, NULL, NULL, 'N;'),
('Admin.Donator.*', 1, NULL, NULL, 'N;'),
('Admin.Donator.Admin', 0, NULL, NULL, 'N;'),
('Admin.Donator.Create', 0, NULL, NULL, 'N;'),
('Admin.Donator.Index', 0, NULL, NULL, 'N;'),
('Admin.Donator.Update', 0, NULL, NULL, 'N;'),
('Admin.Donator.View', 0, NULL, NULL, 'N;'),
('Admin.Event.*', 1, NULL, NULL, 'N;'),
('Admin.Event.Admin', 0, NULL, NULL, 'N;'),
('Admin.Event.Create', 0, NULL, NULL, 'N;'),
('Admin.Event.CreateGallery', 0, NULL, NULL, 'N;'),
('Admin.Event.Index', 0, NULL, NULL, 'N;'),
('Admin.Event.Update', 0, NULL, NULL, 'N;'),
('Admin.Event.View', 0, NULL, NULL, 'N;'),
('Admin.Eventactivity.*', 1, NULL, NULL, 'N;'),
('Admin.Eventactivity.Admin', 0, NULL, NULL, 'N;'),
('Admin.Eventactivity.Create', 0, NULL, NULL, 'N;'),
('Admin.Eventactivity.Index', 0, NULL, NULL, 'N;'),
('Admin.Eventactivity.Update', 0, NULL, NULL, 'N;'),
('Admin.Eventactivity.View', 0, NULL, NULL, 'N;'),
('Admin.Eventagenda.*', 1, NULL, NULL, 'N;'),
('Admin.Eventagenda.Admin', 0, NULL, NULL, 'N;'),
('Admin.Eventagenda.Create', 0, NULL, NULL, 'N;'),
('Admin.Eventagenda.Index', 0, NULL, NULL, 'N;'),
('Admin.Eventagenda.Update', 0, NULL, NULL, 'N;'),
('Admin.Eventagenda.View', 0, NULL, NULL, 'N;'),
('Admin.Eventphoto.*', 1, NULL, NULL, 'N;'),
('Admin.Eventphoto.Admin', 0, NULL, NULL, 'N;'),
('Admin.Eventphoto.Create', 0, NULL, NULL, 'N;'),
('Admin.Eventphoto.Index', 0, NULL, NULL, 'N;'),
('Admin.Eventphoto.Update', 0, NULL, NULL, 'N;'),
('Admin.Eventphoto.View', 0, NULL, NULL, 'N;'),
('Admin.Eventtype.*', 1, NULL, NULL, 'N;'),
('Admin.Eventtype.Admin', 0, NULL, NULL, 'N;'),
('Admin.Eventtype.Create', 0, NULL, NULL, 'N;'),
('Admin.Eventtype.Index', 0, NULL, NULL, 'N;'),
('Admin.Eventtype.Update', 0, NULL, NULL, 'N;'),
('Admin.Eventtype.View', 0, NULL, NULL, 'N;'),
('Admin.Gallery.*', 1, NULL, NULL, 'N;'),
('Admin.Gallery.AjaxUpload', 0, NULL, NULL, 'N;'),
('Admin.Gallery.ChangeData', 0, NULL, NULL, 'N;'),
('Admin.Gallery.Order', 0, NULL, NULL, 'N;'),
('Admin.Mailattachment.*', 1, NULL, NULL, 'N;'),
('Admin.Mailattachment.Admin', 0, NULL, NULL, 'N;'),
('Admin.Mailattachment.Create', 0, NULL, NULL, 'N;'),
('Admin.Mailattachment.Index', 0, NULL, NULL, 'N;'),
('Admin.Mailattachment.Update', 0, NULL, NULL, 'N;'),
('Admin.Mailattachment.View', 0, NULL, NULL, 'N;'),
('Admin.Mailinbox.*', 1, NULL, NULL, 'N;'),
('Admin.Mailinbox.Admin', 0, NULL, NULL, 'N;'),
('Admin.Mailinbox.Create', 0, NULL, NULL, 'N;'),
('Admin.Mailinbox.CreateGallery', 0, NULL, NULL, 'N;'),
('Admin.Mailinbox.Index', 0, NULL, NULL, 'N;'),
('Admin.Mailinbox.Update', 0, NULL, NULL, 'N;'),
('Admin.Mailinbox.View', 0, NULL, NULL, 'N;'),
('Admin.Mailoutbox.*', 1, NULL, NULL, 'N;'),
('Admin.Mailoutbox.Admin', 0, NULL, NULL, 'N;'),
('Admin.Mailoutbox.Create', 0, NULL, NULL, 'N;'),
('Admin.Mailoutbox.CreateGallery', 0, NULL, NULL, 'N;'),
('Admin.Mailoutbox.Index', 0, NULL, NULL, 'N;'),
('Admin.Mailoutbox.Update', 0, NULL, NULL, 'N;'),
('Admin.Mailoutbox.View', 0, NULL, NULL, 'N;'),
('Admin.Mailtemplate.*', 1, NULL, NULL, 'N;'),
('Admin.Mailtemplate.Admin', 0, NULL, NULL, 'N;'),
('Admin.Mailtemplate.Create', 0, NULL, NULL, 'N;'),
('Admin.Mailtemplate.Index', 0, NULL, NULL, 'N;'),
('Admin.Mailtemplate.Update', 0, NULL, NULL, 'N;'),
('Admin.Mailtemplate.View', 0, NULL, NULL, 'N;'),
('Admin.Mailtype.*', 1, NULL, NULL, 'N;'),
('Admin.Mailtype.Admin', 0, NULL, NULL, 'N;'),
('Admin.Mailtype.Create', 0, NULL, NULL, 'N;'),
('Admin.Mailtype.Index', 0, NULL, NULL, 'N;'),
('Admin.Mailtype.Update', 0, NULL, NULL, 'N;'),
('Admin.Mailtype.View', 0, NULL, NULL, 'N;'),
('Admin.Mosque.*', 1, NULL, NULL, 'N;'),
('Admin.Mosque.Admin', 0, NULL, NULL, 'N;'),
('Admin.Mosque.Create', 0, NULL, NULL, 'N;'),
('Admin.Mosque.CreateGallery', 0, NULL, NULL, 'N;'),
('Admin.Mosque.GeneratePDF', 0, NULL, NULL, 'N;'),
('Admin.Mosque.Index', 0, NULL, NULL, 'N;'),
('Admin.Mosque.Report', 0, NULL, NULL, 'N;'),
('Admin.Mosque.Update', 0, NULL, NULL, 'N;'),
('Admin.Mosque.View', 0, NULL, NULL, 'N;'),
('Admin.Mosqueagent.*', 1, NULL, NULL, 'N;'),
('Admin.Mosqueagent.Admin', 0, NULL, NULL, 'N;'),
('Admin.Mosqueagent.Create', 0, NULL, NULL, 'N;'),
('Admin.Mosqueagent.Index', 0, NULL, NULL, 'N;'),
('Admin.Mosqueagent.Update', 0, NULL, NULL, 'N;'),
('Admin.Mosqueagent.View', 0, NULL, NULL, 'N;'),
('Admin.Mosquephoto.*', 1, NULL, NULL, 'N;'),
('Admin.Mosquephoto.Admin', 0, NULL, NULL, 'N;'),
('Admin.Mosquephoto.Create', 0, NULL, NULL, 'N;'),
('Admin.Mosquephoto.Index', 0, NULL, NULL, 'N;'),
('Admin.Mosquephoto.Update', 0, NULL, NULL, 'N;'),
('Admin.Mosquephoto.View', 0, NULL, NULL, 'N;'),
('Admin.Mosquetype.*', 1, NULL, NULL, 'N;'),
('Admin.Mosquetype.Admin', 0, NULL, NULL, 'N;'),
('Admin.Mosquetype.Create', 0, NULL, NULL, 'N;'),
('Admin.Mosquetype.Index', 0, NULL, NULL, 'N;'),
('Admin.Mosquetype.Update', 0, NULL, NULL, 'N;'),
('Admin.Mosquetype.View', 0, NULL, NULL, 'N;'),
('Admin.Organization.*', 1, NULL, NULL, 'N;'),
('Admin.Organization.Admin', 0, NULL, NULL, 'N;'),
('Admin.Organization.Create', 0, NULL, NULL, 'N;'),
('Admin.Organization.Index', 0, NULL, NULL, 'N;'),
('Admin.Organization.Update', 0, NULL, NULL, 'N;'),
('Admin.Organizationaccesslevel.*', 1, NULL, NULL, 'N;'),
('Admin.Organizationaccesslevel.Admin', 0, NULL, NULL, 'N;'),
('Admin.Organizationaccesslevel.Create', 0, NULL, NULL, 'N;'),
('Admin.Organizationaccesslevel.Index', 0, NULL, NULL, 'N;'),
('Admin.Organizationaccesslevel.Update', 0, NULL, NULL, 'N;'),
('Admin.Organizationaccesslevel.View', 0, NULL, NULL, 'N;'),
('Admin.Organizationaccesslevelpermission.*', 1, NULL, NULL, 'N;'),
('Admin.Organizationaccesslevelpermission.Admin', 0, NULL, NULL, 'N;'),
('Admin.Organizationaccesslevelpermission.Create', 0, NULL, NULL, 'N;'),
('Admin.Organizationaccesslevelpermission.Index', 0, NULL, NULL, 'N;'),
('Admin.Organizationaccesslevelpermission.Update', 0, NULL, NULL, 'N;'),
('Admin.Organizationaccesslevelpermission.View', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranch.*', 1, NULL, NULL, 'N;'),
('Admin.Organizationbranch.Admin', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranch.Create', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranch.Index', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranch.Update', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranch.View', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountry.*', 1, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountry.Admin', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountry.Create', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountry.Index', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountry.Update', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountry.View', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountrycommittee.*', 1, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountrycommittee.Admin', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountrycommittee.Create', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountrycommittee.Index', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountrycommittee.Update', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountrycommittee.View', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountrycommitteeuser.*', 1, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountrycommitteeuser.Admin', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountrycommitteeuser.Create', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountrycommitteeuser.Index', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountrycommitteeuser.Update', 0, NULL, NULL, 'N;'),
('Admin.Organizationbranchcountrycommitteeuser.View', 0, NULL, NULL, 'N;'),
('Admin.Organizationposition.*', 1, NULL, NULL, 'N;'),
('Admin.Organizationposition.Admin', 0, NULL, NULL, 'N;'),
('Admin.Organizationposition.Create', 0, NULL, NULL, 'N;'),
('Admin.Organizationposition.Index', 0, NULL, NULL, 'N;'),
('Admin.Organizationposition.Update', 0, NULL, NULL, 'N;'),
('Admin.Organizationposition.View', 0, NULL, NULL, 'N;'),
('Admin.Organizationtype.*', 1, NULL, NULL, 'N;'),
('Admin.Organizationtype.Admin', 0, NULL, NULL, 'N;'),
('Admin.Organizationtype.Create', 0, NULL, NULL, 'N;'),
('Admin.Organizationtype.Index', 0, NULL, NULL, 'N;'),
('Admin.Organizationtype.Update', 0, NULL, NULL, 'N;'),
('Admin.Organizationtype.View', 0, NULL, NULL, 'N;'),
('Admin.Organizationuser.*', 1, NULL, NULL, 'N;'),
('Admin.Organizationuser.Admin', 0, NULL, NULL, 'N;'),
('Admin.Organizationuser.Create', 0, NULL, NULL, 'N;'),
('Admin.Organizationuser.Index', 0, NULL, NULL, 'N;'),
('Admin.Organizationuser.Update', 0, NULL, NULL, 'N;'),
('Admin.Organizationuser.View', 0, NULL, NULL, 'N;'),
('Admin.Organizationuseraccesslevel.*', 1, NULL, NULL, 'N;'),
('Admin.Organizationuseraccesslevel.Admin', 0, NULL, NULL, 'N;'),
('Admin.Organizationuseraccesslevel.Create', 0, NULL, NULL, 'N;'),
('Admin.Organizationuseraccesslevel.Index', 0, NULL, NULL, 'N;'),
('Admin.Organizationuseraccesslevel.Update', 0, NULL, NULL, 'N;'),
('Admin.Organizationuseraccesslevel.View', 0, NULL, NULL, 'N;'),
('Admin.Task.*', 1, NULL, NULL, 'N;'),
('Admin.Task.Admin', 0, NULL, NULL, 'N;'),
('Admin.Task.Create', 0, NULL, NULL, 'N;'),
('Admin.Task.Index', 0, NULL, NULL, 'N;'),
('Admin.Task.Update', 0, NULL, NULL, 'N;'),
('Admin.Task.View', 0, NULL, NULL, 'N;'),
('Authenticated', 2, NULL, NULL, 'N;'),
('Guest', 2, NULL, NULL, 'N;'),
('Site.*', 1, NULL, NULL, 'N;'),
('Site.Contact', 0, NULL, NULL, 'N;'),
('Site.Error', 0, NULL, NULL, 'N;'),
('Site.Index', 0, NULL, NULL, 'N;'),
('Site.Login', 0, NULL, NULL, 'N;'),
('Site.Logout', 0, NULL, NULL, 'N;'),
('Translate.Edit.*', 1, NULL, NULL, 'N;'),
('Translate.Edit.Admin', 0, NULL, NULL, 'N;'),
('Translate.Edit.Create', 0, NULL, NULL, 'N;'),
('Translate.Edit.Missing', 0, NULL, NULL, 'N;'),
('Translate.Edit.Missingdelete', 0, NULL, NULL, 'N;'),
('Translate.Edit.Update', 0, NULL, NULL, 'N;'),
('Translate.Translate.*', 1, NULL, NULL, 'N;'),
('Translate.Translate.Index', 0, NULL, NULL, 'N;');

-- --------------------------------------------------------

--
-- Table structure for table `auth_item_child`
--

DROP TABLE IF EXISTS `auth_item_child`;
CREATE TABLE IF NOT EXISTS `auth_item_child` (
  `parent` varchar(64) NOT NULL,
  `child` varchar(64) NOT NULL,
  PRIMARY KEY (`parent`,`child`),
  KEY `child` (`child`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `auth_item_child`
--

INSERT INTO `auth_item_child` (`parent`, `child`) VALUES
('Authenticated', 'Admin.Beneficiary.*'),
('Authenticated', 'Admin.Beneficiary.Admin'),
('Authenticated', 'Admin.Beneficiary.Create'),
('Authenticated', 'Admin.Beneficiary.Index'),
('Authenticated', 'Admin.Beneficiary.Update'),
('Authenticated', 'Admin.Beneficiary.View'),
('Authenticated', 'Admin.Beneficiarydisabled.*'),
('Authenticated', 'Admin.Beneficiarydisabled.Admin'),
('Authenticated', 'Admin.Beneficiarydisabled.Create'),
('Authenticated', 'Admin.Beneficiarydisabled.Index'),
('Authenticated', 'Admin.Beneficiarydisabled.Update'),
('Authenticated', 'Admin.Beneficiarydisabled.View'),
('Authenticated', 'Admin.Beneficiaryfamilymembers.*'),
('Authenticated', 'Admin.Beneficiaryfamilymembers.Admin'),
('Authenticated', 'Admin.Beneficiaryfamilymembers.Create'),
('Authenticated', 'Admin.Beneficiaryfamilymembers.Index'),
('Authenticated', 'Admin.Beneficiaryfamilymembers.Update'),
('Authenticated', 'Admin.Beneficiaryfamilymembers.View'),
('Authenticated', 'Admin.Beneficiaryfinance.*'),
('Authenticated', 'Admin.Beneficiaryfinance.Admin'),
('Authenticated', 'Admin.Beneficiaryfinance.Create'),
('Authenticated', 'Admin.Beneficiaryfinance.Index'),
('Authenticated', 'Admin.Beneficiaryfinance.Update'),
('Authenticated', 'Admin.Beneficiaryfinance.View'),
('Authenticated', 'Admin.Beneficiaryhome.*'),
('Authenticated', 'Admin.Beneficiaryhome.Admin'),
('Authenticated', 'Admin.Beneficiaryhome.Create'),
('Authenticated', 'Admin.Beneficiaryhome.Index'),
('Authenticated', 'Admin.Beneficiaryhome.Update'),
('Authenticated', 'Admin.Beneficiaryhome.View'),
('Authenticated', 'Admin.Beneficiaryorphan.*'),
('Authenticated', 'Admin.Beneficiaryorphan.Admin'),
('Authenticated', 'Admin.Beneficiaryorphan.Create'),
('Authenticated', 'Admin.Beneficiaryorphan.Index'),
('Authenticated', 'Admin.Beneficiaryorphan.Update'),
('Authenticated', 'Admin.Beneficiaryorphan.View'),
('Authenticated', 'Admin.Beneficiarypaterfamilias.*'),
('Authenticated', 'Admin.Beneficiarypaterfamilias.Admin'),
('Authenticated', 'Admin.Beneficiarypaterfamilias.Create'),
('Authenticated', 'Admin.Beneficiarypaterfamilias.Index'),
('Authenticated', 'Admin.Beneficiarypaterfamilias.Update'),
('Authenticated', 'Admin.Beneficiarypaterfamilias.View'),
('Authenticated', 'Admin.Beneficiarypoor.*'),
('Authenticated', 'Admin.Beneficiarypoor.Admin'),
('Authenticated', 'Admin.Beneficiarypoor.Create'),
('Authenticated', 'Admin.Beneficiarypoor.Index'),
('Authenticated', 'Admin.Beneficiarypoor.Update'),
('Authenticated', 'Admin.Beneficiarypoor.View'),
('Authenticated', 'Admin.Beneficiaryrelation.*'),
('Authenticated', 'Admin.Beneficiaryrelation.Admin'),
('Authenticated', 'Admin.Beneficiaryrelation.Create'),
('Authenticated', 'Admin.Beneficiaryrelation.Index'),
('Authenticated', 'Admin.Beneficiaryrelation.Update'),
('Authenticated', 'Admin.Beneficiaryrelation.View'),
('Authenticated', 'Admin.Beneficiaryresearchnotes.*'),
('Authenticated', 'Admin.Beneficiaryresearchnotes.Admin'),
('Authenticated', 'Admin.Beneficiaryresearchnotes.Create'),
('Authenticated', 'Admin.Beneficiaryresearchnotes.Index'),
('Authenticated', 'Admin.Beneficiaryresearchnotes.Update'),
('Authenticated', 'Admin.Beneficiaryresearchnotes.View'),
('Authenticated', 'Admin.Beneficiarystudent.*'),
('Authenticated', 'Admin.Beneficiarystudent.Admin'),
('Authenticated', 'Admin.Beneficiarystudent.Create'),
('Authenticated', 'Admin.Beneficiarystudent.Index'),
('Authenticated', 'Admin.Beneficiarystudent.Update'),
('Authenticated', 'Admin.Beneficiarystudent.View'),
('Authenticated', 'Admin.Beneficiarystudentclass.*'),
('Authenticated', 'Admin.Beneficiarystudentclass.Admin'),
('Authenticated', 'Admin.Beneficiarystudentclass.Create'),
('Authenticated', 'Admin.Beneficiarystudentclass.Index'),
('Authenticated', 'Admin.Beneficiarystudentclass.Update'),
('Authenticated', 'Admin.Beneficiarystudentclass.View'),
('Authenticated', 'Admin.Beneficiaryteacher.*'),
('Authenticated', 'Admin.Beneficiaryteacher.Admin'),
('Authenticated', 'Admin.Beneficiaryteacher.Create'),
('Authenticated', 'Admin.Beneficiaryteacher.Index'),
('Authenticated', 'Admin.Beneficiaryteacher.Update'),
('Authenticated', 'Admin.Beneficiaryteacher.View'),
('Authenticated', 'Admin.Beneficiarywidow.*'),
('Authenticated', 'Admin.Beneficiarywidow.Admin'),
('Authenticated', 'Admin.Beneficiarywidow.Create'),
('Authenticated', 'Admin.Beneficiarywidow.Index'),
('Authenticated', 'Admin.Beneficiarywidow.Update'),
('Authenticated', 'Admin.Beneficiarywidow.View'),
('Authenticated', 'Admin.City.*'),
('Authenticated', 'Admin.City.Admin'),
('Authenticated', 'Admin.City.Create'),
('Authenticated', 'Admin.City.GetCities'),
('Authenticated', 'Admin.City.Index'),
('Authenticated', 'Admin.City.Update'),
('Authenticated', 'Admin.City.View'),
('Authenticated', 'Admin.Country.*'),
('Authenticated', 'Admin.Country.Admin'),
('Authenticated', 'Admin.Country.Create'),
('Authenticated', 'Admin.Country.Index'),
('Authenticated', 'Admin.Country.Update'),
('Authenticated', 'Admin.Country.View'),
('Authenticated', 'Admin.Default.*'),
('Authenticated', 'Admin.Default.Error'),
('Authenticated', 'Admin.Default.Index'),
('Authenticated', 'Admin.Default.Login'),
('Authenticated', 'Admin.Default.Logout'),
('Authenticated', 'Admin.Donator.*'),
('Authenticated', 'Admin.Donator.Admin'),
('Authenticated', 'Admin.Donator.Create'),
('Authenticated', 'Admin.Donator.Index'),
('Authenticated', 'Admin.Donator.Update'),
('Authenticated', 'Admin.Donator.View'),
('Authenticated', 'Admin.Event.*'),
('Authenticated', 'Admin.Event.Admin'),
('Authenticated', 'Admin.Event.Create'),
('Authenticated', 'Admin.Event.CreateGallery'),
('Authenticated', 'Admin.Event.Index'),
('Authenticated', 'Admin.Event.Update'),
('Authenticated', 'Admin.Event.View'),
('Authenticated', 'Admin.Eventactivity.*'),
('Authenticated', 'Admin.Eventactivity.Admin'),
('Authenticated', 'Admin.Eventactivity.Create'),
('Authenticated', 'Admin.Eventactivity.Index'),
('Authenticated', 'Admin.Eventactivity.Update'),
('Authenticated', 'Admin.Eventactivity.View'),
('Authenticated', 'Admin.Eventagenda.*'),
('Authenticated', 'Admin.Eventagenda.Admin'),
('Authenticated', 'Admin.Eventagenda.Create'),
('Authenticated', 'Admin.Eventagenda.Index'),
('Authenticated', 'Admin.Eventagenda.Update'),
('Authenticated', 'Admin.Eventagenda.View'),
('Authenticated', 'Admin.Eventphoto.*'),
('Authenticated', 'Admin.Eventphoto.Admin'),
('Authenticated', 'Admin.Eventphoto.Create'),
('Authenticated', 'Admin.Eventphoto.Index'),
('Authenticated', 'Admin.Eventphoto.Update'),
('Authenticated', 'Admin.Eventphoto.View'),
('Authenticated', 'Admin.Eventtype.*'),
('Authenticated', 'Admin.Eventtype.Admin'),
('Authenticated', 'Admin.Eventtype.Create'),
('Authenticated', 'Admin.Eventtype.Index'),
('Authenticated', 'Admin.Eventtype.Update'),
('Authenticated', 'Admin.Eventtype.View'),
('Authenticated', 'Admin.Gallery.*'),
('Authenticated', 'Admin.Gallery.AjaxUpload'),
('Authenticated', 'Admin.Gallery.ChangeData'),
('Authenticated', 'Admin.Gallery.Order'),
('Authenticated', 'Admin.Mailattachment.*'),
('Authenticated', 'Admin.Mailattachment.Admin'),
('Authenticated', 'Admin.Mailattachment.Create'),
('Authenticated', 'Admin.Mailattachment.Index'),
('Authenticated', 'Admin.Mailattachment.Update'),
('Authenticated', 'Admin.Mailattachment.View'),
('Authenticated', 'Admin.Mailinbox.*'),
('Authenticated', 'Admin.Mailinbox.Admin'),
('Authenticated', 'Admin.Mailinbox.Create'),
('Authenticated', 'Admin.Mailinbox.CreateGallery'),
('Authenticated', 'Admin.Mailinbox.Index'),
('Authenticated', 'Admin.Mailinbox.Update'),
('Authenticated', 'Admin.Mailinbox.View'),
('Authenticated', 'Admin.Mailoutbox.*'),
('Authenticated', 'Admin.Mailoutbox.Admin'),
('Authenticated', 'Admin.Mailoutbox.Create'),
('Authenticated', 'Admin.Mailoutbox.CreateGallery'),
('Authenticated', 'Admin.Mailoutbox.Index'),
('Authenticated', 'Admin.Mailoutbox.Update'),
('Authenticated', 'Admin.Mailoutbox.View'),
('Authenticated', 'Admin.Mailtemplate.*'),
('Authenticated', 'Admin.Mailtemplate.Admin'),
('Authenticated', 'Admin.Mailtemplate.Create'),
('Authenticated', 'Admin.Mailtemplate.Index'),
('Authenticated', 'Admin.Mailtemplate.Update'),
('Authenticated', 'Admin.Mailtemplate.View'),
('Authenticated', 'Admin.Mailtype.*'),
('Authenticated', 'Admin.Mailtype.Admin'),
('Authenticated', 'Admin.Mailtype.Create'),
('Authenticated', 'Admin.Mailtype.Index'),
('Authenticated', 'Admin.Mailtype.Update'),
('Authenticated', 'Admin.Mailtype.View'),
('Authenticated', 'Admin.Mosque.*'),
('Authenticated', 'Admin.Mosque.Admin'),
('Authenticated', 'Admin.Mosque.Create'),
('Authenticated', 'Admin.Mosque.CreateGallery'),
('Authenticated', 'Admin.Mosque.GeneratePDF'),
('Authenticated', 'Admin.Mosque.Index'),
('Authenticated', 'Admin.Mosque.Report'),
('Authenticated', 'Admin.Mosque.Update'),
('Authenticated', 'Admin.Mosque.View'),
('Authenticated', 'Admin.Mosqueagent.*'),
('Authenticated', 'Admin.Mosqueagent.Admin'),
('Authenticated', 'Admin.Mosqueagent.Create'),
('Authenticated', 'Admin.Mosqueagent.Index'),
('Authenticated', 'Admin.Mosqueagent.Update'),
('Authenticated', 'Admin.Mosqueagent.View'),
('Authenticated', 'Admin.Mosquephoto.*'),
('Authenticated', 'Admin.Mosquephoto.Admin'),
('Authenticated', 'Admin.Mosquephoto.Create'),
('Authenticated', 'Admin.Mosquephoto.Index'),
('Authenticated', 'Admin.Mosquephoto.Update'),
('Authenticated', 'Admin.Mosquephoto.View'),
('Authenticated', 'Admin.Mosquetype.*'),
('Authenticated', 'Admin.Mosquetype.Admin'),
('Authenticated', 'Admin.Mosquetype.Create'),
('Authenticated', 'Admin.Mosquetype.Index'),
('Authenticated', 'Admin.Mosquetype.Update'),
('Authenticated', 'Admin.Mosquetype.View'),
('Authenticated', 'Admin.Organization.*'),
('Authenticated', 'Admin.Organization.Admin'),
('Authenticated', 'Admin.Organization.Create'),
('Authenticated', 'Admin.Organization.Index'),
('Authenticated', 'Admin.Organization.Update'),
('Authenticated', 'Admin.Organizationaccesslevel.*'),
('Authenticated', 'Admin.Organizationaccesslevel.Admin'),
('Authenticated', 'Admin.Organizationaccesslevel.Create'),
('Authenticated', 'Admin.Organizationaccesslevel.Index'),
('Authenticated', 'Admin.Organizationaccesslevel.Update'),
('Authenticated', 'Admin.Organizationaccesslevel.View'),
('Authenticated', 'Admin.Organizationaccesslevelpermission.*'),
('Authenticated', 'Admin.Organizationaccesslevelpermission.Admin'),
('Authenticated', 'Admin.Organizationaccesslevelpermission.Create'),
('Authenticated', 'Admin.Organizationaccesslevelpermission.Index'),
('Authenticated', 'Admin.Organizationaccesslevelpermission.Update'),
('Authenticated', 'Admin.Organizationaccesslevelpermission.View'),
('Authenticated', 'Admin.Organizationbranch.*'),
('Authenticated', 'Admin.Organizationbranch.Admin'),
('Authenticated', 'Admin.Organizationbranch.Create'),
('Authenticated', 'Admin.Organizationbranch.Index'),
('Authenticated', 'Admin.Organizationbranch.Update'),
('Authenticated', 'Admin.Organizationbranch.View'),
('Authenticated', 'Admin.Organizationbranchcountry.*'),
('Authenticated', 'Admin.Organizationbranchcountry.Admin'),
('Authenticated', 'Admin.Organizationbranchcountry.Create'),
('Authenticated', 'Admin.Organizationbranchcountry.Index'),
('Authenticated', 'Admin.Organizationbranchcountry.Update'),
('Authenticated', 'Admin.Organizationbranchcountry.View'),
('Authenticated', 'Admin.Organizationbranchcountrycommittee.*'),
('Authenticated', 'Admin.Organizationbranchcountrycommittee.Admin'),
('Authenticated', 'Admin.Organizationbranchcountrycommittee.Create'),
('Authenticated', 'Admin.Organizationbranchcountrycommittee.Index'),
('Authenticated', 'Admin.Organizationbranchcountrycommittee.Update'),
('Authenticated', 'Admin.Organizationbranchcountrycommittee.View'),
('Authenticated', 'Admin.Organizationbranchcountrycommitteeuser.*'),
('Authenticated', 'Admin.Organizationbranchcountrycommitteeuser.Admin'),
('Authenticated', 'Admin.Organizationbranchcountrycommitteeuser.Create'),
('Authenticated', 'Admin.Organizationbranchcountrycommitteeuser.Index'),
('Authenticated', 'Admin.Organizationbranchcountrycommitteeuser.Update'),
('Authenticated', 'Admin.Organizationbranchcountrycommitteeuser.View'),
('Authenticated', 'Admin.Organizationposition.*'),
('Authenticated', 'Admin.Organizationposition.Admin'),
('Authenticated', 'Admin.Organizationposition.Create'),
('Authenticated', 'Admin.Organizationposition.Index'),
('Authenticated', 'Admin.Organizationposition.Update'),
('Authenticated', 'Admin.Organizationposition.View'),
('Authenticated', 'Admin.Organizationtype.*'),
('Authenticated', 'Admin.Organizationtype.Admin'),
('Authenticated', 'Admin.Organizationtype.Create'),
('Authenticated', 'Admin.Organizationtype.Index'),
('Authenticated', 'Admin.Organizationtype.Update'),
('Authenticated', 'Admin.Organizationtype.View'),
('Authenticated', 'Admin.Organizationuser.*'),
('Authenticated', 'Admin.Organizationuser.Admin'),
('Authenticated', 'Admin.Organizationuser.Create'),
('Authenticated', 'Admin.Organizationuser.Index'),
('Authenticated', 'Admin.Organizationuser.Update'),
('Authenticated', 'Admin.Organizationuser.View'),
('Authenticated', 'Admin.Organizationuseraccesslevel.*'),
('Authenticated', 'Admin.Organizationuseraccesslevel.Admin'),
('Authenticated', 'Admin.Organizationuseraccesslevel.Create'),
('Authenticated', 'Admin.Organizationuseraccesslevel.Index'),
('Authenticated', 'Admin.Organizationuseraccesslevel.Update'),
('Authenticated', 'Admin.Organizationuseraccesslevel.View'),
('Authenticated', 'Admin.Task.*'),
('Authenticated', 'Admin.Task.Admin'),
('Authenticated', 'Admin.Task.Create'),
('Authenticated', 'Admin.Task.Index'),
('Authenticated', 'Admin.Task.Update'),
('Authenticated', 'Admin.Task.View'),
('Authenticated', 'Site.*'),
('Authenticated', 'Site.Contact'),
('Authenticated', 'Site.Error'),
('Authenticated', 'Site.Index'),
('Authenticated', 'Site.Login'),
('Authenticated', 'Site.Logout'),
('Authenticated', 'Translate.Edit.*'),
('Authenticated', 'Translate.Edit.Admin'),
('Authenticated', 'Translate.Edit.Create'),
('Authenticated', 'Translate.Edit.Missing'),
('Authenticated', 'Translate.Edit.Missingdelete'),
('Authenticated', 'Translate.Edit.Update'),
('Authenticated', 'Translate.Translate.*'),
('Authenticated', 'Translate.Translate.Index');

-- --------------------------------------------------------

--
-- Table structure for table `auth_rights`
--

DROP TABLE IF EXISTS `auth_rights`;
CREATE TABLE IF NOT EXISTS `auth_rights` (
  `itemname` varchar(64) NOT NULL,
  `type` int(11) NOT NULL,
  `weight` int(11) NOT NULL,
  PRIMARY KEY (`itemname`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `auth_assignment`
--
ALTER TABLE `auth_assignment`
  ADD CONSTRAINT `auth_assignment_ibfk_1` FOREIGN KEY (`itemname`) REFERENCES `auth_item` (`name`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `auth_item_child`
--
ALTER TABLE `auth_item_child`
  ADD CONSTRAINT `auth_item_child_ibfk_1` FOREIGN KEY (`parent`) REFERENCES `auth_item` (`name`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `auth_item_child_ibfk_2` FOREIGN KEY (`child`) REFERENCES `auth_item` (`name`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `auth_rights`
--
ALTER TABLE `auth_rights`
  ADD CONSTRAINT `auth_rights_ibfk_1` FOREIGN KEY (`itemname`) REFERENCES `auth_item` (`name`) ON DELETE CASCADE ON UPDATE CASCADE;
SET FOREIGN_KEY_CHECKS=1;

		");
	}

	public function down() {
		echo "m141224_021845_create_authenticated_user_permissions_and_assign_it_to_saad does not support migration down.\n";
		return false;
	}

	/*
// Use safeUp/safeDown to do migration with transaction
public function safeUp()
{
}

public function safeDown()
{
}
 */
}